config/routes.rb
GadgetsKeeper::Application.routes.draw do
  resources :user_sessions

  get 'login' => 'user_sessions#new', as: :login
  post 'logout' => 'user_sessions#destroy', as: :logout
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :username, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def not_authenticated
    redirect_to login_url, :alert => t('login.first_login_message')
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  layout 'login'

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:username], params[:password])
      redirect_back_or_to('/', notice: t('login.success_message'))
    else
      flash.now[:error] = t 'login.fail_message'
      render action: "new"
    end
  end

  def destroy
    logout
    redirect_to(login_url, notice: t('login.logout_message'))
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GadgetsKeeper</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Gadgets Keeper</title>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container ptl">

      <%= yield %>

    </div>

  </body>
</html>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, method: :post, class: 'form-signin mtl' do %>

  <h2 class="form-signin-heading">Please sign in</h2>

  <%= text_field_tag :email, params[:username], placeholder: 'Username', class: 'form-control mvs' %>

  <%= password_field_tag :password, params[:password], placeholder: 'Password', class: 'form-control mvs' %>

  <%= submit_tag 'Log In', class: 'btn btn-lg btn-primary btn-block mtm' %>

<% end %>

app/views/user_sessions/new.html.erb
<%= render 'form' %>